server:
  port: 1000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample
    username: root
    password: Admin@1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: group1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

# Custom app-specific topic names
myapp:
  kafka:
    topic: myKafkaTest
    error-topic: error-topic
    employee-batch-topic: employee-batch-topic

##management:
##  endpoints:
##   web:
##     exposure:
##        include: prometheus
##  metrics:
##    enable:
##      process: true
##  prometheus:
##   metrics:
##      export:
##       enabled: true
