package com.example.demo.constants;

public enum Category {
FOOD,
ELECTRICITY,
DAILY_COMMUTE,
OUTSTATION_COMMUTE,
OFFICE_PURPOSE_COMMUTE,
HOME_BILLS,
ONLINE_PURCHASE,
UPI_TRANSACTIONS_CREDIT,
UPI_TRANSACTIONS_DEBIT,
DEBIT_CARD_TRANSACTIONS_DEBIT,
CREDIT_CARD_TRANSACTIONS_CREDIT,
CREDIT_CARD_TRANSACTIONS_DEBIT,
BANK_TRANSFER_DEBIT,
BANK_TRANSFER_CREDIT,
CHEQUE_CREDIT,
CHEQUE_DEBIT,
WIRED_TRANSFER_DEBIT,
WIRED_TRANSFER_CREDIT




}
