openapi: 3.1.0
info:
  title: User Profile Service API
  description: Handles user profile CRUD and activity history
  version: 1.0.0

paths:
  /users:
    post:
      summary: Create new user profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfileRequest'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfileResponse'
        '400':
          description: Invalid input

  /users/{userId}:
    get:
      summary: Get user profile by ID
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: User profile found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfileResponse'
        '404':
          description: User not found

    put:
      summary: Update user profile
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfileUpdateRequest'
      responses:
        '200':
          description: User profile updated
        '400':
          description: Invalid input
        '404':
          description: User not found

    delete:
      summary: Delete user profile
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: User deleted
        '404':
          description: User not found

  /users/{userId}/history:
    get:
      summary: Get user's activity history (add/update/delete events)
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: User activity history fetched
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserActivityHistoryResponse'
        '404':
          description: User not found

components:
  schemas:
    UserProfileRequest:
      type: object
      required: [name, email]
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
        address:
          type: string

    UserProfileUpdateRequest:
      type: object
      properties:
        name:
          type: string
        phone:
          type: string
        address:
          type: string

    UserProfileResponse:
      type: object
      properties:
        userId:
          type: string
          format: uuid
        name:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
        address:
          type: string
        createdAt:
          type: string
          format: date-time

    UserActivityHistoryResponse:
      type: object
      properties:
        userId:
          type: string
          format: uuid
        history:
          type: array
          items:
            $ref: '#/components/schemas/ActivityEvent'

    ActivityEvent:
      type: object
      properties:
        eventType:
          type: string
          enum: [CREATED, UPDATED, DELETED]
        timestamp:
          type: string
          format: date-time
        changes:
          type: object
          additionalProperties: true
