- name: Cleanup Redundant PRs and Branches from CD Automation
  if: github.event.pull_request != null
  uses: GlueOps/github-actions-cleanup-redundant-cd-prs@v0.2.0
  with:
    pr_number: ${{ github.event.pull_request.number }}
    gh_token: ${{ secrets.GITHUB_TOKEN }}
